### ISSUE TITLE
Minor typo with the config file for black quartz generation

### ISSUE THREAD

**Issue by Wizzerinus** [MelnCat/ActuallySubtractions#10]
Very minor typo, but this setting says `laserRelayLoss` :(

https://github.com/MelnCat/ActuallyAdditions/blob/port/1.20.1/src/main/java/de/ellpeck/actuallyadditions/mod/config/CommonConfig.java#L79

**Comment by MelnCat** [comment]
Fixed in 1.2.14.8.
