### ISSUE TITLE
empowerer depowered

### ISSUE THREAD

**Issue by Hadies-Alchemist** [MelnCat/ActuallySubtractions#12]
the empowerer doesn't appear to work. Can't open the ui, can only put the main component in. can't feed it power.

**Comment by MelnCat** [comment]
Could you send a video and/or a list of steps for reproduction?

**Comment by Hadies-Alchemist** [comment]
craft empowerer, place it down. No ui appears when right clicking. Cannot feed power into it as energy cables don't connect to it. Also won't charge when placed adjacent to energy blocks that should be able to feed it power. Can only feed ingredient to its main slot which appear but can't do anything with them.

**Comment by MelnCat** [comment]
The empowerer is a multiblock structure, and won't do anything on its own. You'll need to place it in a cross shape surrounded by display stands, and power the display stands.

**Comment by Hadies-Alchemist** [comment]
It would be nice if that was stated in the guide book but there are seemingly missing entries

**Comment by Hadies-Alchemist** [comment]
![Uploading 2024-11-25_15.35.49.png…]()
