### ISSUE TITLE
Player Interface Crashes When Items Are Removed From A Player's Inventory

### ISSUE THREAD

**Issue by CraftyZombie** [MelnCat/ActuallySubtractions#15]
Minecraft: 1.20.1
Forge: 47.3.12
Mod: 1.2.14.7

Issue: Attempting to extract from a player's inventory using the Player Interface alongside another block with the needed capabilities causing that block to throw a ticking entity error.

Steps to reproduce:
1. Build a contraption like such:
![2024-11-30_22 11 03](https://github.com/user-attachments/assets/826b8039-d6c8-4334-967c-5bf480b640c7)
2. Put items into your inventory. The hopper will start filtering them out.
3. The game crashes.

**Comment by CraftyZombie** [comment]
Just realized that this happens when you attempt to insert items as well.

**Comment by MelnCat** [comment]
Fixed in 1.2.14.8.

**Comment by CraftyZombie** [comment]
THANK YOU
