### ISSUE TITLE
[BUG] FARMER_HOE threw an exception 

### ISSUE THREAD

**Issue by ScottDTA** [MelnCat/ActuallySubtractions#2]
Issue with compatibility with Mine Colonies.

https://github.com/ldtteam/minecolonies/issues/10133

**Comment by MelnCat** [comment]
I'll fix this quickly

**Comment by MelnCat** [comment]
Fixed in 1.2.14.2 https://github.com/MelnCat/ActuallyAdditions/commit/a5aae32c8ee35d8c4530e6a7ee875bde81f17ee7
