### ISSUE TITLE
Crash when using Minecolonies

### ISSUE THREAD

**Issue by Thodor12** [MelnCat/ActuallySubtractions#3]
Hello,

A user of our mod reported a crash when using this mod. 
Your Worm item has an `onHoe` method that automatically assumes existence of a player, which crashes our Farmer AI because they use the tool modification event to attempt to till soil to farmland.

Considering you only require the level, you should probably use `BlockToolModificationEvent#getLevel()` instead of `BlockToolModificationEvent#getPlayer().getLevel()`.

Related to https://github.com/ldtteam/minecolonies/issues/10133

**Comment by MelnCat** [comment]
I'll fix this in the next release.

**Comment by MelnCat** [comment]
Fixed in 1.2.14.2 https://github.com/MelnCat/ActuallyAdditions/commit/a5aae32c8ee35d8c4530e6a7ee875bde81f17ee7
