### ISSUE TITLE
In-Game Guide still obtainable without Patchouli

### ISSUE THREAD

**Issue by TheTimvh1** [MelnCat/ActuallySubtractions#4]
Hey, just wanted to report an issue I discovered by accident.  I was playing the mod and totally forgot Patchouli was required for the Actually Additions Manual.  That, however, isn't the "issue" I speak of, as that's completely understandable as it is intended behavior; rather, it's the fact that the book is still obtainable without it, and those who may not be as savvy as I when it comes to modded Minecraft will ultimately experience a crash if they try opening the book.  Thanks.

**Comment by MelnCat** [comment]
I'll go add a fallback message in case it's not installed

**Comment by MelnCat** [comment]
Fixed in https://github.com/MelnCat/ActuallyAdditions/commit/baf4f0ea1acb118ea8e6ad2f1a17a07921058e97
