### ISSUE TITLE
Items that hold energy (drill, rings, batteries, teleport staff, etc.) don't show empty version in JEI (causing recipe to not be viewable)

### ISSUE THREAD

**Issue by trav90** [MelnCat/ActuallySubtractions#6]
Minecraft 1.20.1
Forge 47.3.10
Actually Subtractions 1.2.14.5
Patchouli 1.20.1-84
JEI 15.19.0.89

JEI is only displaying batteries, drills, rings, etc. with a full charge of CF. Because the "uncharged" items aren't viewable in JEI the recipes aren't either. I am able to force the items to be viewable using CraftTweaker (allowing the recipes to be seen). I recreated the issue using only the mods listed above. I also checked a fresh 1.20.4 instance to confirm it wasn't an issue with Actually Additions itself (it is not so it appears to be an Actually Subtractions 1.20.1-specific issue). Let me know if I can provide any additional information.

**Comment by MelnCat** [comment]
I'll look into it.

**Comment by trav90** [comment]
Thank you!

**Comment by MelnCat** [comment]
Fixed by removing distinction between charged and uncharged item in JEI

**Comment by trav90** [comment]
Thanks so much! Appreciate it!
