### ISSUE TITLE
[Request] EMI Support

### ISSUE THREAD

**Issue by BOLTMAGIC** [MelnCat/ActuallySubtractions#9]
Hey, it would be nice to have EMI support. 
If you use EMI with Actually Subtractions there are no recipes. 
JEI:
![1](https://github.com/user-attachments/assets/c11c6429-28c2-4a0e-8f10-fea6e8e9acd3)

EMI:
![2](https://github.com/user-attachments/assets/c9f7e506-5772-46cb-ab10-421750becc87)

EMI and JEI:
![3](https://github.com/user-attachments/assets/e9351c14-9f9b-4cb7-8b6b-c420a7a6ecb3)

Thanks a lot!

**Comment by BOLTMAGIC** [comment]
ActuallySubtractions-1.20.1-1.2.14.7+mc1.20.1.jar

emi-1.1.16+1.20.1+forge

jei-1.20.1-forge-15.12.2.51.jar

**Comment by Wizzerinus** [comment]
![image](https://github.com/user-attachments/assets/92b98f6a-dc88-4c30-9d55-d9500bac810c)

Works for me on 1.2.14.6, EMI 1.1.13, JEI 15.19.5.99, so something else might be fishy

**Comment by BOLTMAGIC** [comment]
looks like the release version from JEI (15.12.2.51) is not compatible. the beta version 15.20.0.105 works great!
thx a lot!
